select
  uuid,
  ride.estimation.estimationUuid as view_uuid,
  type,
  timeMs as time_ms,
  datetime(timestamp_trunc(timestamp_millis(timeMs), second), 'Asia/Seoul') as time_kr,
  caller.userId as user_id,
  caller.userAgent AS user_agent,
  caller.appsflyerId AS appsflyer_id,
  ride.estimation.distanceMeters AS distance_meters,
  ride.estimation.durationSeconds AS duration_seconds,
  ride.estimation.maxCost AS max_cost,
  ride.estimation.minCost AS min_cost,
  ride.createdAtMs as created_at_ms,
  datetime(timestamp_trunc(timestamp_millis(ride.createdAtMs), second), 'Asia/Seoul') as created_at_kr,
  ride.id AS ride_id,
  ride.rideType AS ride_type,
  ride.vehicleId AS vehicle_id,
  ride.origin.address AS origin_address,
  ride.origin.name AS origin_name,
  ride.origin.lat AS origin_lat,
  ride.origin.lng AS origin_lng,
  ride.destination.address AS destination_address,
  ride.destination.name AS destination_name,
  ride.destination.lat AS destination_lat,
  ride.destination.lng AS destination_lng,
  ride.destinationEtaMs AS destination_eta_ms,
  ride.originSource AS origin_source,
  ride.destinationSource AS destination_source,
  ride.originEtaMs AS origin_eta_ms,
  ride.rawOriginEtaMs AS raw_origin_eta_ms,
  ride.etaModelCreatedAtMs AS eta_model_created_at_ms,
  ride.priceRating AS price_rating,
  ride.couponId AS coupon_id,
  ride.defaultCouponId AS default_coupon_id,
  ride.paymentMethodId AS payment_method_id,
  ride.reviewRatingByUser AS review_rating_by_user,
  ride.routeDistanceMeters AS route_distance_meters,
  ride.routeUuid AS route_uuid,
  ride.status,
  appReviewed AS app_reviewed,
  satisfied,
  date_kr
from
  tada.server_log_parquet
where
  date_kr = '{execute_date}'
  and type = 'USER_REQUEST_RIDE'